### ISSUE TITLE
Application title Windows notification 

### ISSUE THREAD

**Issue by harg** [ncruces/zenity#46] opened 2023-01-16 21:06 UTC
Thank you for your library!

Is it possible to display the application name instead of 'Microsoft.Explorer.Notification...'
![image](https://user-images.githubusercontent.com/34398/212764295-32093df6-8ce1-4ab4-b3c6-72bbd65aa661.png)

**Comment by ncruces** [comment] 2023-01-19 16:45
This is a duplicate of #37.

[`Shell_NotifyIconW`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyiconw) used [here](https://github.com/ncruces/zenity/blob/master/notify_windows.go) doesn't allow for more.

But, again, I'm open to suggestions.

**Closed** 2023-08-03 16:46 UTC
Labels: enhancement
